### ISSUE TITLE
Error invoking callback

### ISSUE THREAD

**Issue by WeirdPhrog** [oqyh/cs2-Vote-GoldKingZ#6]
2024-04-20 20:40:01.325 +03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Vote_GoldKingZ.VoteBanned.HandleMenuALL(CCSPlayerController Caller, ChatMenuOption option, Int32 TargetPlayersUserID) in C:\Users\oqyh\Documents\cs2-Vote-GoldKingZ\Vote Banned\VoteBanned.cs:line 1180
   at Vote_GoldKingZ.VoteBanned.<>c__DisplayClass5_3.<OnEventPlayerChat>b__3(CCSPlayerController Caller, ChatMenuOption option) in C:\Users\oqyh\Documents\cs2-Vote-GoldKingZ\Vote Banned\VoteBanned.cs:line 413
   at CounterStrikeSharp.API.Modules.Menu.BaseMenuInstance.OnKeyPress(CCSPlayerController player, Int32 key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Menu/BaseMenu.cs:line 130
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 64
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by oqyh** [comment]
> 2024-04-20 20:40:01.325 +03:00 [EROR] (cssharp:Core) Error invoking callback System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Vote_GoldKingZ.VoteBanned.HandleMenuALL(CCSPlayerController Caller, ChatMenuOption option, Int32 TargetPlayersUserID) in C:\Users\oqyh\Documents\cs2-Vote-GoldKingZ\Vote Banned\VoteBanned.cs:line 1180 at Vote_GoldKingZ.VoteBanned.<>c__DisplayClass5_3.b__3(CCSPlayerController Caller, ChatMenuOption option) in C:\Users\oqyh\Documents\cs2-Vote-GoldKingZ\Vote Banned\VoteBanned.cs:line 413 at CounterStrikeSharp.API.Modules.Menu.BaseMenuInstance.OnKeyPress(CCSPlayerController player, Int32 key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Menu/BaseMenu.cs:line 130 at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 64 at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr) --- End of inner exception stack trace --- at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr) at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Delegate.DynamicInvokeImpl(Object[] args) at CounterStrikeSharp.API.Core.FunctionReference.b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100


Fixed
https://github.com/oqyh/cs2-Vote-GoldKingZ/releases/tag/1.0.9
